/* ============================================================
   content.js — YOUR EDITABLE LISTS
   This is the file you'll touch most. Add a project or a gallery
   photo by adding a line here — the website builds the rest.
   ============================================================ */

/* -----------------------------------------------------------
   PROJECTS
   Each project is one { ... } block. To add a project, copy an
   existing block, paste it, and change the words.
     slug  = a short id with no spaces (used in the web address)
     title = shown on hover and on the project's own page
     cover = the image on the Projects grid
     blurb = the short line under the title on the project page
     body  = paragraphs on the project page (add as many as you like)
     images= extra images shown down the project page (optional)
   ----------------------------------------------------------- */
const PROJECTS = [
  {
    slug: "ecobite",
    title: "EcoBite",
    link: "ecobite.html",          // EcoBite has its own full case-study page
    cover: "images/ecobite/hero.jpg",
    blurb: "A sustainability-focused mobile app concept.",
    body: [
      "Write about EcoBite here — the brief, your role, the process you went through, and what the outcome was.",
      "You can add as many paragraphs as you like by adding more lines inside the square brackets."
    ],
    images: [
      "images/projects/ecobite-1.jpg",
      "images/projects/ecobite-2.jpg"
    ]
  },
  {
    slug: "project-two",
    title: "Soon...",
    cover: "images/projects/project-two.jpg",
    blurb: "",
    body: [],
    images: []
  },
  {
    slug: "project-three",
    title: "Soon...",
    cover: "images/projects/project-three.jpg",
    blurb: "",
    body: [],
    images: []
  }
];

/* -----------------------------------------------------------
   GALLERY
   Just a list of photo filenames (in images/gallery/).
   Add a photo by dropping the file in that folder and adding
   its filename to this list. The masonry + zoom handle the rest.
   ----------------------------------------------------------- */
const GALLERY = [
  "images/gallery/digi-film-01.jpg",
  "images/gallery/digi-film-02.jpg",
  "images/gallery/digi-film-03.jpg",
  "images/gallery/digi-film-04.jpg",
  "images/gallery/digi-film-05.jpg",
  "images/gallery/digi-film-06.jpg",
  "images/gallery/digi-film-07.jpg",
  "images/gallery/digi-film-08.jpg",
  "images/gallery/digi-film-09.jpg",
  "images/gallery/digi-film-10.jpg",
  "images/gallery/digi-film-11.jpg",
  "images/gallery/digi-film-12.jpg",
  "images/gallery/digi-film-13.jpg",
  "images/gallery/digi-film-14.jpg",
  "images/gallery/digi-film-15.jpg",
  "images/gallery/digi-film-16.jpg",
  "images/gallery/digi-film-17.jpg",
  "images/gallery/digi-film-18.jpg",
  "images/gallery/digi-film-19.jpg",
  "images/gallery/digi-film-20.jpg",
  "images/gallery/digi-film-21.jpg",
  "images/gallery/digi-film-22.jpg",
  "images/gallery/digi-film-23.jpg",
  "images/gallery/digi-film-24.jpg",
  "images/gallery/digi-film-25.jpg",
  "images/gallery/digi-film-26.jpg",
  "images/gallery/digi-film-27.jpg",
  "images/gallery/digi-film-28.jpg",
  "images/gallery/digi-film-29.jpg",
  "images/gallery/digi-film-30.jpg",
  "images/gallery/digi-film-31.jpg",
  "images/gallery/digi-film-32.jpg",
  "images/gallery/digi-film-33.jpg",
  "images/gallery/digi-film-34.jpg",
  "images/gallery/digi-film-35.jpg",
  "images/gallery/digi-film-36.jpg",
  "images/gallery/digi-film-37.jpg",
  "images/gallery/digi-film-38.jpg",
  "images/gallery/digi-film-39.jpg",
  "images/gallery/digi-film-40.jpg",
  "images/gallery/digi-film-41.jpg",
  "images/gallery/digi-film-42.jpg",
  "images/gallery/digi-film-43.jpg",
  "images/gallery/digi-film-44.jpg",
  "images/gallery/digi-film-45.jpg",
  "images/gallery/digi-film-46.jpg",
  "images/gallery/digi-film-47.jpg",
  "images/gallery/digi-film-48.jpg",
  "images/gallery/digi-film-49.jpg",
  "images/gallery/digi-film-50.jpg",
  "images/gallery/digi-film-51.jpg",
  "images/gallery/digi-film-52.jpg",
  "images/gallery/digi-film-53.jpg",
  "images/gallery/digi-ozzette-01.jpg",
  "images/gallery/digi-ozzette-02.jpg",
  "images/gallery/digi-ozzette-03.jpg",
  "images/gallery/digi-ozzette-04.jpg",
  "images/gallery/digi-ozzette-05.jpg",
  "images/gallery/digi-ozzette-06.jpg",
  "images/gallery/digi-ozzette-07.jpg",
  "images/gallery/digi-ozzette-08.jpg",
  "images/gallery/digi-ozzette-09.jpg",
  "images/gallery/digi-ozzette-10.jpg",
  "images/gallery/digi-ozzette-11.jpg",
  "images/gallery/digi-ozzette-12.jpg",
  "images/gallery/digi-ozzette-13.jpg",
  "images/gallery/digi-ozzette-14.jpg",
  "images/gallery/digi-ozzette-15.jpg",
  "images/gallery/digi-ozzette-16.jpg",
  "images/gallery/digi-ozzette-17.jpg",
  "images/gallery/digi-ozzette-18.jpg",
  "images/gallery/digi-ozzette-19.jpg",
  "images/gallery/film-01.jpg",
  "images/gallery/film-02.jpg",
  "images/gallery/film-03.jpg",
  "images/gallery/film-04.jpg",
  "images/gallery/film-05.jpg",
  "images/gallery/film-06.jpg",
  "images/gallery/film-07.jpg",
  "images/gallery/film-08.jpg",
  "images/gallery/film-09.jpg",
  "images/gallery/film-10.jpg",
  "images/gallery/film-11.jpg",
  "images/gallery/neutrals-01.jpg",
  "images/gallery/neutrals-02.jpg",
  "images/gallery/neutrals-03.jpg",
  "images/gallery/neutrals-04.jpg",
  "images/gallery/neutrals-05.jpg",
  "images/gallery/neutrals-06.jpg",
  "images/gallery/neutrals-07.jpg",
  "images/gallery/neutrals-08.jpg",
  "images/gallery/neutrals-09.jpg",
  "images/gallery/neutrals-10.jpg",
  "images/gallery/neutrals-11.jpg",
  "images/gallery/neutrals-12.jpg",
  "images/gallery/neutrals-13.jpg",
  "images/gallery/neutrals-14.jpg",
  "images/gallery/neutrals-15.jpg",
  "images/gallery/neutrals-16.jpg",
  "images/gallery/neutrals-17.jpg",
  "images/gallery/neutrals-18.jpg",
  "images/gallery/neutrals-19.jpg",
  "images/gallery/neutrals-20.jpg",
  "images/gallery/neutrals-21.jpg",
  "images/gallery/neutrals-22.jpg",
  "images/gallery/neutrals-23.jpg",
  "images/gallery/neutrals-24.jpg",
  "images/gallery/neutrals-25.jpg",
  "images/gallery/neutrals-26.jpg",
  "images/gallery/neutrals-27.jpg",
  "images/gallery/neutrals-28.jpg",
  "images/gallery/neutrals-29.jpg",
  "images/gallery/neutrals-30.jpg",
  "images/gallery/neutrals-31.jpg",
  "images/gallery/neutrals-32.jpg",
  "images/gallery/neutrals-33.jpg",
  "images/gallery/neutrals-34.jpg",
  "images/gallery/neutrals-35.jpg",
  "images/gallery/neutrals-36.jpg",
  "images/gallery/neutrals-37.jpg",
  "images/gallery/neutrals-38.jpg",
  "images/gallery/neutrals-39.jpg",
  "images/gallery/colorful-01.jpg",
  "images/gallery/colorful-02.jpg",
  "images/gallery/colorful-03.jpg",
  "images/gallery/colorful-04.jpg",
  "images/gallery/colorful-05.jpg",
  "images/gallery/colorful-06.jpg",
  "images/gallery/colorful-07.jpg",
  "images/gallery/colorful-08.jpg",
  "images/gallery/colorful-09.jpg",
  "images/gallery/colorful-10.jpg",
  "images/gallery/colorful-11.jpg",
  "images/gallery/colorful-12.jpg",
  "images/gallery/colorful-13.jpg",
  "images/gallery/colorful-14.jpg",
  "images/gallery/colorful-15.jpg",
  "images/gallery/colorful-16.jpg",
  "images/gallery/colorful-17.jpg",
  "images/gallery/colorful-18.jpg",
  "images/gallery/colorful-19.jpg",
  "images/gallery/event-01.jpg",
  "images/gallery/event-02.jpg",
  "images/gallery/event-03.jpg",
  "images/gallery/event-04.jpg",
  "images/gallery/event-05.jpg",
  "images/gallery/event-06.jpg",
  "images/gallery/event-07.jpg",
  "images/gallery/event-08.jpg",
  "images/gallery/event-09.jpg",
  "images/gallery/event-10.jpg",
  "images/gallery/event-11.jpg",
  "images/gallery/event-12.jpg",
  "images/gallery/event-13.jpg",
  "images/gallery/event-14.jpg",
  "images/gallery/event-15.jpg",
  "images/gallery/event-16.jpg",
  "images/gallery/event-17.jpg",
  "images/gallery/event-18.jpg",
  "images/gallery/event-19.jpg",
  "images/gallery/event-20.jpg",
  "images/gallery/event-21.jpg",
  "images/gallery/event-22.jpg",
  "images/gallery/event-23.jpg",
  "images/gallery/event-24.jpg",
  "images/gallery/event-25.jpg",
  "images/gallery/event-26.jpg",
  "images/gallery/event-27.jpg",
  "images/gallery/event-28.jpg",
  "images/gallery/event-29.jpg",
  "images/gallery/event-30.jpg",
  "images/gallery/event-31.jpg",
  "images/gallery/event-32.jpg",
  "images/gallery/product-01.jpg",
  "images/gallery/product-02.jpg",
  "images/gallery/product-03.jpg",
  "images/gallery/product-04.jpg",
  "images/gallery/product-05.jpg",
  "images/gallery/product-06.jpg",
  "images/gallery/product-07.jpg",
  "images/gallery/product-08.jpg",
  "images/gallery/product-09.jpg",
  "images/gallery/product-10.jpg",
  "images/gallery/product-11.jpg",
  "images/gallery/product-12.jpg",
  "images/gallery/product-13.jpg",
  "images/gallery/product-14.jpg",
  "images/gallery/product-15.jpg",
  "images/gallery/product-16.jpg",
  "images/gallery/product-17.jpg",
  "images/gallery/product-18.jpg",
  "images/gallery/product-19.jpg",
  "images/gallery/product-20.jpg",
  "images/gallery/product-21.jpg",
  "images/gallery/product-22.jpg",
  "images/gallery/product-23.jpg",
  "images/gallery/animal-01.jpg",
  "images/gallery/animal-02.jpg",
  "images/gallery/animal-03.jpg",
  "images/gallery/animal-04.jpg",
  "images/gallery/animal-05.jpg",
  "images/gallery/animal-06.jpg",
  "images/gallery/animal-07.jpg",
  "images/gallery/animal-08.jpg",
  "images/gallery/animal-09.jpg",
  "images/gallery/animal-10.jpg",
  "images/gallery/animal-11.jpg",
  "images/gallery/animal-12.jpg",
  "images/gallery/animal-13.jpg",
  "images/gallery/animal-14.jpg",
  "images/gallery/animal-15.jpg",
  "images/gallery/animal-16.jpg",
  "images/gallery/animal-17.jpg",
  "images/gallery/animal-18.jpg",
  "images/gallery/animal-19.jpg",
  "images/gallery/animal-20.jpg",
  "images/gallery/animal-21.jpg",
  "images/gallery/bw-02.jpg",
  "images/gallery/bw-09.jpg",
  "images/gallery/bw-03.jpg",
  "images/gallery/bw-01.jpg",
  "images/gallery/bw-11.jpg",
  "images/gallery/bw-04.jpg",
  "images/gallery/bw-05.jpg",
  "images/gallery/bw-06.jpg",
  "images/gallery/bw-07.jpg",
  "images/gallery/bw-08.jpg",
  "images/gallery/bw-10.jpg",
  "images/gallery/bw-12.jpg"
];
